services:
  dockwatch:
    container_name: backend
    image: inspectorgadget12/dockwatch-core:latest
    restart: always
    environment:
      - DOCKWATCH_DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - "8080:8080"
